<?php
/**
 * phpcs:ignoreFile -- As this file is auto-generated, it should be excluded from linting.
 *
 * Asset settings generated by webpack.
 *
 * WARNING: Do not edit this file!
 * It will be created and updated automatically whenever new assets are created.
 */

define( 'UCHI_FRONTEND_CSS', 'frontend-b1d33d38.css' );
define( 'UCHI_FRONTEND_JS', 'frontend-6003d4a9.js' );

define( 'UCHI_FRONTEND_DEPENDENCIES', [] );
define( 'UCHI_VERSION', '0.1.1' );
