<?php
/**
 * phpcs:ignoreFile -- As this file is auto-generated, it should be excluded from linting.
 *
 * Asset settings generated by webpack.
 *
 * WARNING: Do not edit this file!
 * It will be created and updated automatically whenever new assets are created.
 */

define( 'SMPL_FRONTEND_CSS', 'frontend.css' );
define( 'SMPL_FRONTEND_JS', 'frontend.js' );

define( 'SMPL_FRONTEND_DEPENDENCIES', [] );
define( 'SMPL_VERSION', '0.0.1' );
